apiVersion: v1
kind: Secret
metadata:
  name: astravector-secret
type: Opaque
stringData:
  ASTRAVECTOR_NEXUS_USERNAME: ""
  ASTRAVECTOR_NEXUS_PASSWORD: ""
  ASTRAVECTOR_DB_URL: ""
  ASTRAVECTOR_API_KEY: ""
  ASTRAVECTOR_QDRANT_URL: ""
  ASTRAVECTOR_QDRANT_API_KEY: ""
  ASTRAVECTOR_GATEWAY_TRUST_TOKEN: ""
